#!/usr/bin/env bash

PWD=$(pwd)

if [ "$#" -ne 1 ]; then
    echo "Usage: ./add_domain maildomain.tld"
    exit 1
fi

source .conf
DOMAIN=$1

sed "s/<DOMAIN>/$DOMAIN/g" $PWD/sqls/add_domain.sql | mysql -sfu root -p$DB_ROOT_PASS
