#!/usr/bin/env bash

USERID=$(id -u)

if [[ $USERID -ne 0 ]]; then
	echo "This script must be run as root"
	exit 1
fi

PWD=$(pwd)

if [ "$#" -ne 1 ]; then
    echo "Usage: ./add_domain maildomain.tld"
    exit 1
fi

source .conf
DOMAIN=$1

sed "s/<DOMAIN>/$DOMAIN/g" $PWD/sqls/add_domain.sql | mysql -sfu root -p$DB_ROOT_PASS


curl -s https://dl.eff.org/certbot-auto > $PWD/certbot-auto
chmod a+x $PWD/certbot-auto
$PWD/certbot-auto certonly --standalone --debug -d $DOMAIN -d mail.$DOMAIN -n --agree-tos -m $EMAIL

