#!/usr/bin/env bash

USERID=$(id -u)

if [[ $USERID -ne 0 ]]; then
        echo "This script must be run as root"
        exit 1
fi

PWD=$(pwd)

if [[ $1 = "-v" ]]; then
        OUT="/dev/stdout"
else
    	OUT="/dev/null"
fi


yum -y remove postfix dovecot mariadb-server > $OUT 
rm -rf /var/lib/mysql
rm -rf /etc/dovecot
rm -rf /etc/postfix
rm -rf /var/spool/postfix
rm -rf /var/vmail
rm -f $PWD/certbot-auto
rm -f $PWD/.conf
rm -f $PWD/setup.log
userdel vmail
