#!/usr/bin/env bash

USERID=$(id -u)

if [[ $USERID -ne 0 ]]; then
        echo "This script must be run as root"
        exit 1
fi

PWD=$(pwd)

if [ "$#" -ne 1 ]; then
	echo "Usage: ./delete_user maildomain.tld"
	exit 1
fi

source .conf

DOMAIN=$1

sed "s <DOMAIN> $DOMAIN g" $PWD/sqls/delete_domain.sql | mysql -sfu root -p$DB_ROOT_PASS
