#!/usr/bin/env bash

ETC_HOSTS=/etc/hosts
PUBLIC_IP=$(curl -s ifconfig.me)
HOSTNAME=$(hostname)
USERID=$(id -u)
YUM="/usr/bin/yum -y"

read -p 'Enter domain name: ' DOMAIN
read -p 'Enter admin email: ' EMAIL

MAILDOMAIN="mail.$DOMAIN"
IMAPDOMAIN="imap.$DOMAIN"
SMTPDOMAIN="smtp.$DOMAIN"

WEBMASTEREMAIL="webmaster@$DOMAIN"

# desplays user info
function display_info() {
	echo ":: Installation Details ::"
	echo "\tPublic IP: $PUBLIC_IP"
	echo "\tHostname: $HOSTNAME"
	echo "\tDomain name: $DOMAIN"
	echo "\tMail subdomain: $MAILDOMAIN"
	echo "\tIMAP subdomain: $IMAPDOMAIN"
	echo "\tSMTP subdomain: $SMTPDOMAIN"
	echo "\tAdmin email: $EMAIL"
	echo "\tWebmaster email: $WEBMASTEREMAIL"
	echo
}

# checks if root access is granted
function checkroot() {
	if [[ $USERID -ne 0 ]]; then
		echo "This script must be run as root"
		exit 1
	fi
}

# sets up a mysql database server
function setup_db() {
	$YUM update
	$YUM install mariadb-server mariadb-client
	systemctl start mariadb

	mysql -sfu root < "sqls/mysql_secure_installation.sql"
	mysql -sfu root -pemailroot! < "sqls/db.sql"
}


# adds entry to hosts
function addhost() {
	IP=$1
	FQDN=$2
	HOSTNAME=$3

	HOSTS_LINE="$IP\t$DOMAIN\t$HOSTNAME"
	if [ -n "$(grep $HOSTNAME $ETC_HOSTS)" ]
	then
		echo "$HOSTNAME already exists : $(grep $HOSTNAME $ETC_HOSTS)"
	else
		echo "Adding $HOSTNAME to your $ETC_HOSTS";
		sudo -- sh -c -e "echo -e '$HOSTS_LINE' >> $ETC_HOSTS";

	if [ -n "$(grep $HOSTNAME $ETC_HOSTS)" ]
		then
			echo -e "$HOSTNAME was added succesfully \n $(grep $HOSTNAME $ETC_HOSTS)";
		else
			echo -e "Failed to Add $HOSTNAME, Try again!";
		fi
	fi
}

# Setup Certbot & TLS certificates for the domain supplied
function setup_certbot() {
	wget https://dl.eff.org/certbot-auto
	chmod a+x ./certbot-auto
	sudo ./certbot-auto certonly --standalone --debug -d $DOMAIN -d $MAILDOMAIN -d $IMAPDOMAIN -d $SMTPDOMAIN -n --agree-tos -m $EMAIL
}

# Setup users & maildirectories
fuction setup_maildir() {
	mkdir /var/vmail
	mkdir /var/vmail/mailboxes
	mkdir -p /var/vmail/sieve/global

	groupadd vmail
	adduser --disabled-login --disabled-password --home /var/vmail -g vmail vmail

	chown -R vmail /var/vmail
	chgrp -R vmail /var/vmail
	chmod -R 770 /var/vmail
}

# Setup Postfix
function setup_postfix() {
	$YUM update
	$YUM install postfix

	addhost $PUBLIC_IP $FQDN $HOSTNAME
	echo $(hostname -f) > /etc/mailname

	postconf -e "myhostname=$HOSTNAME"
	postconf -e "mydomain=$DOMAIN"
	postconf -e "myorigin=\$mydomain"
	postconf -e "inet_interfaces=all"
	postconf -e "inet_protocols=all"

}

# Setup Dovecot
function setup_dovecot() {
	$YUM update
	$YUM install dovecot dovecot-mysql
	systemctl stop dovecot

	# remove all default configuration
	rm -r /etc/dovecot/*

}

# Main procedure
checkroot
setup_db
setup_certbot
setup_dovecot
#setup_postfix
display_info
