#!/usr/bin/env bash

ETC_HOSTS=/etc/hosts
PUBLIC_IP=$(curl -s ifconfig.me)
HOSTNAME=$(hostname)
USERID=$(id -u)
YUM="/usr/bin/yum -y"

read -p 'Enter domain name: ' DOMAIN
read -p 'Enter admin email: ' EMAIL

MAILDOMAIN="mail.$DOMAIN"
IMAPDOMAIN="imap.$DOMAIN"
SMTPDOMAIN="smtp.$DOMAIN"

POSTMASTEREMAIL="postmaster@$DOMAIN"

DB_PASS=$(tr -dc _A-Z-a-z-0-9 < /dev/urandom | head -c15)
DB_ROOT_PASS=$(tr -dc _A-Z-a-z-0-9 < /dev/urandom | head -c15)

# desplays user info
function display_info() {
	echo -e ":: Installation Details ::"
	echo -e "\tPublic IP: $PUBLIC_IP"
	echo -e "\tHostname: $HOSTNAME"
	echo
	echo -e "\tDomain name: $DOMAIN"
	echo -e "\tMail subdomain: $MAILDOMAIN"
	echo -e "\tIMAP subdomain: $IMAPDOMAIN"
	echo -e "\tSMTP subdomain: $SMTPDOMAIN"
	echo
	echo -e "\tAdmin email: $EMAIL"
	echo -e "\tPostmaster email: $POSTMASTEREMAIL"
	echo
	echo -e "\tMySQL root user: root"
	echo -e "\tMySQL root password: $DB_ROOT_PASS"
	echo -e "\tMySQL email db user: vmail"
	echo -e "\tMySQL email db pass: $DB_PASS"
	echo
}

# checks if root access is granted
function checkroot() {
	if [[ $USERID -ne 0 ]]; then
		echo "This script must be run as root"
		exit 1
	fi
}

# sets up a mysql database server
function setup_db() {
	$YUM update
	$YUM install mariadb-server mariadb-client
	
	systemctl enable mariadb
	systemctl start mariadb

	sed "s/<DB_ROOT_PASS>/$DB_ROOT_PASS/g" sqls/mysql_secure_installation.sql | mysql -sfu root
	sed "s/<DB_PASS>/$DB_PASS/g" sqls/db.sql | mysql -sfu root -p$DB_ROOT_PASS
}


# adds entry to hosts
function addhost() {
	IP=$1
	DOMAIN=$2
	HOSTNAME=$3

	HOSTS_LINE="$IP\t$DOMAIN\t$HOSTNAME"
	if [ -n "$(grep $HOSTNAME $ETC_HOSTS)" ]
	then
		echo "$HOSTNAME already exists : $(grep $HOSTNAME $ETC_HOSTS)"
	else
		echo "Adding $HOSTNAME to your $ETC_HOSTS";
		sudo -- sh -c -e "echo -e '$HOSTS_LINE' >> $ETC_HOSTS";

	if [ -n "$(grep $HOSTNAME $ETC_HOSTS)" ]
		then
			echo -e "$HOSTNAME was added succesfully \n $(grep $HOSTNAME $ETC_HOSTS)";
		else
			echo -e "Failed to Add $HOSTNAME, Try again!";
		fi
	fi
}

# Setup Certbot & TLS certificates for the domain supplied
function setup_certbot() {
	curl -s https://dl.eff.org/certbot-auto > certbot-auto
	chmod a+x ./certbot-auto
	./certbot-auto certonly --standalone --debug -d $DOMAIN -n --agree-tos -m $EMAIL
}

# Setup users & maildirectories
function setup_maildir() {
	mkdir -p /var/vmail/mailboxes
	mkdir -p /var/vmail/sieve/global

	groupadd vmail
	useradd -d /var/vmail -g vmail -s /sbin/nologin -M vmail

	cp confs/vmail/sieve/global/spam-global.sieve /var/vmail/sieve/global/spam-global.sieve
        cp confs/vmail/sieve/global/learn-spam.sieve /var/vmail/sieve/global/learn-spam.sieve
        cp confs/vmail/sieve/global/learn-ham.sieve /var/vmail/sieve/global/learn-ham.sieve

	chown -R vmail /var/vmail
	chgrp -R vmail /var/vmail
	chmod -R 770 /var/vmail
}

# Setup Postfix
function setup_postfix() {
	$YUM update
	$YUM install postfix

	addhost $PUBLIC_IP $DOMAIN $HOSTNAME
	echo $(hostname -f) > /etc/mailname
	
	systemctl stop postfix
	systemctl enable postfix

	rm /etc/postfix/{master.cf,main.cf}
	mkdir /etc/postfix/sql

	sed "s/<DOMAIN>/$DOMAIN/g; s/<PUBLIC_IP>/$PUBLIC_IP/g; s/<HOSTNAME>/$HOSTNAME/g" confs/postfix/main.cf > /etc/postfix/main.cf

	cp confs/postfix/master.cf /etc/postfix/master.cf
	cp confs/postfix/submission_header_cleanup /etc/postfix/submission_header_cleanup

	for filename in confs/postfix/sql/*.cf; do
    		[ -e "$filename" ] || continue
		sed "s/<DB_PASS>/$DB_PASS/g" $filename > /etc/postfix/sql/$(basename "$filename")		
 	done

	chmod -R 640 /etc/postfix/sql

	touch /etc/postfix/without_ptr
	touch /etc/postfix/postscreen_access	
}

# Setup Dovecot
function setup_dovecot() {
	$YUM update
	$YUM install dovecot dovecot-mysql
	
	systemctl enable dovecot
	systemctl stop dovecot

	# remove all default configuration
	rm -r /etc/dovecot/*

	sed "s/<DOMAIN>/$DOMAIN/g; s/<ADDRESS>/$POSTMASTEREMAIL/g" confs/dovecot/dovecot.conf > /etc/dovecot/dovecot.conf
	sed "s/<DB_PASS>/$DB_PASS/g" confs/dovecot/dovecot-sql.conf > /etc/dovecot/dovecot-sql.conf
	chmod 440 /etc/dovecot/dovecot-sql.conf	  
}

# Main procedure
checkroot
setup_db
setup_maildir
setup_certbot
setup_dovecot
setup_postfix
display_info
